export enum Routes {
  Dashboard = 'Dashboard',
  Map = 'Map',
  MapMarker = 'Map Marker',
  StreetView = 'Street View',
  Tables = 'Tables',
  TreeTables = 'TreeTables',
  Charts = 'Charts',
  Cards = 'Cards',
  Contact = 'Contact',
  Calendar = 'Calendar',
  Taskboard = 'Taskboard',
  Pagination = 'Pagination',
  Products = 'Products Catalogues',
}
